package br.com.cp5.DAO;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import br.com.cp5.beans.Quote;

public class QuoteDAO {

    private final String url;
    private final String username;
    private final String password;

    public QuoteDAO(String url, String username, String password) {
        this.url = url;
        this.username = username;
        this.password = password;
    }
    
/*
* drop table quotes;

create table quotes(
	id number generated by default as identity primary key,
	quote varchar(100) not null,
	nota number(2)
);

select * from quotes
*/

    public void inserirCitacao(Quote quote, Integer nota) throws SQLException {
        String sql = "INSERT INTO quotes (quote, nota) VALUES (?, ?)";

        try (Connection conn = DriverManager.getConnection(url, username, password);
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, quote.getQuote());
            pstmt.setObject(2, nota); // Permite que nota seja null
            pstmt.executeUpdate();
        }
    }

    public List<Quote> buscarCitacoes() throws SQLException {
        String sql = "SELECT quote, nota FROM quotes";
        List<Quote> quotes = new ArrayList<>();

        try (Connection conn = DriverManager.getConnection(url, username, password);
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                Quote quote = new Quote();
                quote.setQuote(rs.getString("quote"));
                Integer nota = (Integer) rs.getObject("nota");
                quotes.add(quote);
            }
        }
        return quotes;
    }
}
